/**
 * kb-index-generator — produces a deterministic markdown digest of the
 * workspace's kb state, written to `<kbRoot>/index.md`.
 *
 * The index is the change-detection mechanism for the kb-consolidator
 * agent: the agent reads the bottom-of-file SHA, compares it to the
 * last-seen hash recorded in `consolidator-log.md`, and bails out
 * cheaply when nothing has changed. Only when the SHA differs does it
 * deep-read the changed entries.
 *
 * Output structure (deterministic — same kb state → byte-identical output):
 *
 *   # KB Index
 *   _generated: <iso8601>_
 *
 *   ## Skills (N)
 *   - `name` (mtime: <iso>) — <description first line, ≤ 160 chars>
 *
 *   ## Memory (N)
 *   - `name` (size: B, mtime: <iso>)
 *
 *   ## Agents (N)   ## Workflows (N)   …same shape
 *
 *   ---
 *   INDEX_HASH: <sha256 of the above, minus the timestamp>
 *
 * The `_generated:` timestamp is excluded from the hash so a no-op
 * regen produces the same hash and the consolidator stays cheap.
 */

import { createHash } from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'

interface SkillEntry {
  name: string
  description: string
  mtimeMs: number
}
interface MemoryEntry {
  name: string
  size: number
  mtimeMs: number
}
interface AgentOrWorkflowEntry {
  name: string
  /** First non-empty line of description / role / task. */
  blurb: string
  mtimeMs: number
}

export interface KbIndex {
  /** Markdown rendered for index.md. */
  markdown: string
  /** Stable sha256 over the digest body (no timestamp). Used by
   *  consolidators to short-circuit when nothing has changed. */
  hash: string
  /** Counts per section — useful for tests + telemetry. */
  counts: {
    skills: number
    memory: number
    agents: number
    workflows: number
  }
}

const HEADING_BLURB_LIMIT = 160

export async function buildKbIndex(kbRoot: string): Promise<KbIndex> {
  const skills    = await readSkills(path.join(kbRoot, 'skills'))
  const memory    = await readMemory(path.join(kbRoot, 'memory'))
  const agents    = await readAgentsOrWorkflows(path.join(kbRoot, 'agents'),    'AGENT.md',    'role')
  const workflows = await readAgentsOrWorkflows(path.join(kbRoot, 'workflows'), 'WORKFLOW.md', 'task')

  const lines: string[] = []
  lines.push('# KB Index')
  lines.push('_generated by kb-index-generator on every kb change. The hash at the bottom is what the consolidator uses to decide whether to do work._')
  lines.push('')

  lines.push(`## Skills (${skills.length})`)
  if (skills.length === 0) lines.push('_(none)_')
  for (const s of skills) {
    lines.push(`- \`${s.name}\` (mtime: ${isoOf(s.mtimeMs)}) — ${truncate(s.description)}`)
  }
  lines.push('')

  lines.push(`## Memory (${memory.length})`)
  if (memory.length === 0) lines.push('_(none)_')
  for (const m of memory) {
    lines.push(`- \`${m.name}\` (${m.size} bytes, mtime: ${isoOf(m.mtimeMs)})`)
  }
  lines.push('')

  lines.push(`## Agents (${agents.length})`)
  if (agents.length === 0) lines.push('_(none)_')
  for (const a of agents) {
    lines.push(`- \`${a.name}\` (mtime: ${isoOf(a.mtimeMs)}) — ${truncate(a.blurb)}`)
  }
  lines.push('')

  lines.push(`## Workflows (${workflows.length})`)
  if (workflows.length === 0) lines.push('_(none)_')
  for (const w of workflows) {
    lines.push(`- \`${w.name}\` (mtime: ${isoOf(w.mtimeMs)}) — ${truncate(w.blurb)}`)
  }
  lines.push('')

  // Body hashed BEFORE the timestamp / hash footer is appended.
  const body = lines.join('\n')
  const hash = createHash('sha256').update(body).digest('hex')

  // Final markdown: prepend a generation timestamp comment that is OUTSIDE
  // the hashed body, then the body, then the hash footer.
  const markdown = [
    `<!-- generated: ${new Date().toISOString()} -->`,
    body,
    '---',
    `INDEX_HASH: ${hash}`,
    '',
  ].join('\n')

  return {
    markdown,
    hash,
    counts: {
      skills: skills.length,
      memory: memory.length,
      agents: agents.length,
      workflows: workflows.length,
    },
  }
}

/**
 * Atomically write `<kbRoot>/index.md`. Re-uses the tmp+rename pattern
 * from the rest of the kb writers. Idempotent — writes only when content
 * actually differs (so the kb-watcher doesn't re-fire a feedback loop on
 * its own write).
 */
export async function regenerateKbIndex(kbRoot: string): Promise<KbIndex> {
  const idx = await buildKbIndex(kbRoot)
  const abs = path.join(kbRoot, 'index.md')
  // Skip the write when the body is byte-identical to what's on disk —
  // matters because the kb-watcher will fire on this very write otherwise.
  // We compare on the hash-bearing line, ignoring the timestamp.
  let prior: string | null = null
  try { prior = await fs.readFile(abs, 'utf8') } catch { /* not there — write fresh */ }
  if (prior) {
    const priorHash = (prior.match(/^INDEX_HASH:\s*([a-f0-9]{64})/m) || [])[1]
    if (priorHash === idx.hash) return idx
  }
  await fs.mkdir(kbRoot, { recursive: true })
  const tmp = `${abs}.tmp.${process.pid}.${Date.now()}`
  await fs.writeFile(tmp, idx.markdown)
  await fs.rename(tmp, abs)
  return idx
}

/* ===== readers ===== */

async function readSkills(dir: string): Promise<SkillEntry[]> {
  const out: SkillEntry[] = []
  let names: string[]
  try {
    names = await fs.readdir(dir)
  } catch { return out }
  for (const name of names) {
    const file = path.join(dir, name, 'SKILL.md')
    let stat
    try { stat = await fs.stat(file) } catch { continue }
    if (!stat.isFile()) continue
    let text = ''
    try { text = await fs.readFile(file, 'utf8') } catch { continue }
    out.push({
      name,
      description: extractFrontmatter(text, 'description') ?? '(no description)',
      mtimeMs: stat.mtimeMs,
    })
  }
  out.sort((a, b) => a.name.localeCompare(b.name))
  return out
}

async function readMemory(dir: string): Promise<MemoryEntry[]> {
  const out: MemoryEntry[] = []
  let names: string[]
  try { names = await fs.readdir(dir) } catch { return out }
  for (const name of names) {
    if (!name.endsWith('.md')) continue
    const file = path.join(dir, name)
    let stat
    try { stat = await fs.stat(file) } catch { continue }
    if (!stat.isFile()) continue
    out.push({
      name: name.slice(0, -3),
      size: stat.size,
      mtimeMs: stat.mtimeMs,
    })
  }
  out.sort((a, b) => a.name.localeCompare(b.name))
  return out
}

async function readAgentsOrWorkflows(
  dir: string,
  filename: string,
  blurbField: 'role' | 'task',
): Promise<AgentOrWorkflowEntry[]> {
  const out: AgentOrWorkflowEntry[] = []
  let names: string[]
  try { names = await fs.readdir(dir) } catch { return out }
  for (const name of names) {
    const file = path.join(dir, name, filename)
    let stat
    try { stat = await fs.stat(file) } catch { continue }
    if (!stat.isFile()) continue
    let text = ''
    try { text = await fs.readFile(file, 'utf8') } catch { continue }
    out.push({
      name,
      blurb: extractFrontmatter(text, blurbField) ?? extractFrontmatter(text, 'description') ?? '(no description)',
      mtimeMs: stat.mtimeMs,
    })
  }
  out.sort((a, b) => a.name.localeCompare(b.name))
  return out
}

/* ===== helpers ===== */

/** Ultra-light frontmatter scan — pulls a single string scalar by key
 *  from the YAML frontmatter at the top of a markdown file. Quotes
 *  ('"' or "'") are stripped. Multi-line values not supported (we don't
 *  use them for the index). */
function extractFrontmatter(text: string, key: string): string | null {
  if (!text.startsWith('---')) return null
  const end = text.indexOf('\n---', 3)
  if (end < 0) return null
  const fm = text.slice(3, end)
  const re = new RegExp(`^\\s*${key}\\s*:\\s*(.+?)\\s*$`, 'm')
  const m = re.exec(fm)
  if (!m) return null
  let v = (m[1] ?? '').trim()
  if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
    v = v.slice(1, -1)
  }
  return v.length > 0 ? v : null
}

function truncate(s: string): string {
  const single = s.replace(/\s+/g, ' ').trim()
  return single.length > HEADING_BLURB_LIMIT ? single.slice(0, HEADING_BLURB_LIMIT - 1) + '…' : single
}

function isoOf(ms: number): string {
  return new Date(ms).toISOString()
}
